### ISSUE TITLE
Undefined method error

### ISSUE THREAD

**Issue by Rocksau80** [9506hqwy/redmine_scm_gitlab#2]
The plugin is very useful and worked without flaws for my first tests. But as soon as I added a second repository to a project it ended up with an error:
`I, [2023-10-10T06:53:47.248945 #108647]  INFO -- : [0c203251-d148-4120-a3ce-8699fa2fe280] Processing by RepositoriesController#show as HTML
I, [2023-10-10T06:53:47.249023 #108647]  INFO -- : [0c203251-d148-4120-a3ce-8699fa2fe280]   Parameters: {"id"=>"repo_id", "repository_id"=>"short_id"}
I, [2023-10-10T06:53:47.254589 #108647]  INFO -- : [0c203251-d148-4120-a3ce-8699fa2fe280]   Current user: Me (id=12)
I, [2023-10-10T06:53:52.520530 #108647]  INFO -- : [0c203251-d148-4120-a3ce-8699fa2fe280] Completed 500 Internal Server Error in 5271ms (ActiveRecord: 6.4ms | Allocations: 32151)
F, [2023-10-10T06:53:52.521246 #108647] FATAL -- : [0c203251-d148-4120-a3ce-8699fa2fe280]
[0c203251-d148-4120-a3ce-8699fa2fe280] NoMethodError (undefined method `[]' for nil:NilClass):
[0c203251-d148-4120-a3ce-8699fa2fe280]
[0c203251-d148-4120-a3ce-8699fa2fe280] plugins/redmine_scm_gitlab/lib/redmine_scm_gitlab/gitlab_client.rb:106:in `filesize'
[0c203251-d148-4120-a3ce-8699fa2fe280] plugins/redmine_scm_gitlab/lib/redmine_scm_gitlab/gitlab_adapter.rb:37:in `block in entries'
[0c203251-d148-4120-a3ce-8699fa2fe280] plugins/redmine_scm_gitlab/lib/redmine_scm_gitlab/gitlab_adapter.rb:33:in `map'
[0c203251-d148-4120-a3ce-8699fa2fe280] plugins/redmine_scm_gitlab/lib/redmine_scm_gitlab/gitlab_adapter.rb:33:in `entries'
[0c203251-d148-4120-a3ce-8699fa2fe280] app/models/repository.rb:204:in `scm_entries'
[0c203251-d148-4120-a3ce-8699fa2fe280] app/models/repository.rb:209:in `entries'
[0c203251-d148-4120-a3ce-8699fa2fe280] app/controllers/repositories_controller.rb:89:in `show'
[0c203251-d148-4120-a3ce-8699fa2fe280] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
`
Using latest version of the plugin on Redmine 5.0.5.

**Comment by 9506hqwy** [comment]
Thank for reporting.

This issue was occurred if there is a white space in file name.
I fixed at a9c608a.

Please pull main branch.

**Comment by Rocksau80** [comment]
I'm updating right now and will report the result.

**Comment by Rocksau80** [comment]
Works fine now. Thank you very much.
